name: Categorizacion de comentarios

on:
  workflow_dispatch: # Permite la ejecuci칩n manual desde la pesta침a Actions de GitHub
  schedule:
    - cron: '0 0 * * 0' # Se ejecuta todos los domingos a la medianoche (UTC)

jobs:
  run-categorization:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Usando la misma versi칩n que tu notebook

    - name: Install dependencies
      working-directory: ./notebooks/Categorizacion de sentimientos
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run categorization script
      env:
        API_KEY: ${{ secrets.OPENAI_API_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1 # Puedes cambiar esto si usas otra regi칩n
      working-directory: ./notebooks/Categorizacion de sentimientos
      run: python run_categorization.py
